# Generated by Django 5.2.8 on 2025-11-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userinterest_userprofile_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
