# Generated by Django 5.2.8 on 2025-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug unik untuk URL, misalnya: penerjunan-magang",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Judul blog yang tampil di card dan halaman detail.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Deskripsi singkat untuk card di halaman utama.",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Isi lengkap artikel (boleh beberapa paragraf)."
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        help_text="Relative static path, e.g. 'theme/assets/img/blog/1.jpeg'",
                        max_length=255,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Nama penulis, misalnya 'Kusuma'.", max_length=100
                    ),
                ),
                (
                    "author_image",
                    models.CharField(
                        blank=True,
                        default="theme/assets/img/blog/b6.jpg",
                        help_text="Relative static path untuk avatar penulis.",
                        max_length=255,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="Tag pendek, misalnya 'By Kusuma'.",
                        max_length=100,
                    ),
                ),
                (
                    "published_at",
                    models.DateField(help_text="Tanggal artikel dipublikasikan."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
