# Generated by Django 5.2.8 on 2025-11-29 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Isi komentar")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Waktu ketika komentar dibuat",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Post yang dikomentari",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="public.blogpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User yang memberikan komentar",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
