# Generated by Django 5.2.8 on 2025-12-08 02:10

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Jumlah berapa kali artikel dilihat"
            ),
        ),
    ]
